### ISSUE TITLE
Permission to fork versions for Alien Space Programs

### ISSUE THREAD

**Issue by gordonfpanam** [Galileo88/StockVisualEnhancements#4]
I want to adapt SVE (and SVT) for GregroxMun's Alien Space Programs. The add-ons this depends on have their own quirkiness that make a search / replace of 'Kerbin' with 'Bin' using Module Manager problematic.

But I won't fork this without permission, considering the -NoDerivatives portion of your license.

**Comment by Galileo88** [comment]
Yeah, go for it. Just some simple attribution is needed.
