### ISSUE TITLE
README.md links to wrong version of SVE-textures

### ISSUE THREAD

**Issue by plhosk** [Galileo88/StockVisualEnhancements#7]
README.md (displayed on the page https://github.com/Galileo88/StockVisualEnhancements) links to SVE-textures with this link: https://github.com/Galileo88/StockVisualEnhancements/releases/tag/1.0.2

This should be 1.0.5 for the latest version.

**Comment by Galileo88** [comment]
Thanks. Will fix with the next update, which is in like an hour.
