### ISSUE TITLE
CKAN - Failed to download 

### ISSUE THREAD

**Issue by Jakaya0897** [Galileo88/StockVisualEnhancements#8]
Hey there just wanted to make you aware 

`Module StockVisualEnhancements has not been found. This may be because it is not compatible with the currently installed version of KSP`

as the title says it just won't install it the apply button is greyed out
CKAN - v 1.24
KSP - v 1.4.0

**Comment by Galileo88** [comment]
You may have to reinstall CKAN. I don't do anything with it except ask them to get it working. If you have other questions, I recommend asking them.
